### PR TITLE
Added app icon

### PR DESCRIPTION
**Pull request by jordan-dalby**
Hey, firstly, great project idea!

~~This PR adds a template that's compatible with Unraid, technically the proper way to do this would be to submit the template to the Unraid community repo, but this is a good substitute for now while the project is in early stages.~~

I also added an app icon, I am by no means a graphic designer so it's pretty basic, feel free to reject it if it isn't what you had in mind. I suppose it kind of represents that SuggestArr will be looking at your watch history, represented by the eye and the play icon.
Cheers!

### CODE REVIEW

**Comment by jordan-dalby** [comment]
And actually I just saw it's already on the Unraid store, great!

**Comment by giuseppe99barchetta** [comment]
Hi! Thanks so much for the PR, it’s fantastic! Yes, it’s already in the UnRaid store, but I didn’t add it myself, so I’m trying to find a way to edit the Docker Compose setup there. Unfortunately, I haven’t found a solution yet.

**Comment by jordan-dalby** [comment]
> Hi! Thanks so much for the PR, it’s fantastic! Yes, it’s already in the UnRaid store, but I didn’t add it myself, so I’m trying to find a way to edit the Docker Compose setup there. Unfortunately, I haven’t found a solution yet.

Let me see if I can find the repo it's in, I'll push an update there to match the new docker compose format.

**Comment by giuseppe99barchetta** [comment]
> > Hi! Thanks so much for the PR, it’s fantastic! Yes, it’s already in the UnRaid store, but I didn’t add it myself, so I’m trying to find a way to edit the Docker Compose setup there. Unfortunately, I haven’t found a solution yet.
> 
> Let me see if I can find the repo it's in, I'll push an update there to match the new docker compose format.

Thank you so much! I really appreciate it. I'll hold off on merging until I get an update from you.

**Comment by jordan-dalby** [comment]
> > > Hi! Thanks so much for the PR, it’s fantastic! Yes, it’s already in the UnRaid store, but I didn’t add it myself, so I’m trying to find a way to edit the Docker Compose setup there. Unfortunately, I haven’t found a solution yet.
> > 
> > 
> > Let me see if I can find the repo it's in, I'll push an update there to match the new docker compose format.
> 
> Thank you so much! I really appreciate it. I'll hold off on merging until I get an update from you.

Looks like the template is already up-to-date.
https://github.com/JamsRepos/Unraid-Templates/blob/main/templates/suggestarr.xml

I've submitted a PR to change the logo though :)
https://github.com/JamsRepos/Unraid-Templates/pull/3

**Comment by JamsRepos** [comment]
If you ever need anything in the future with the Unraid Template feel free to ping me, if you want more uniformality and have it hosted here then we can also do that if you wish, would allow people to be able to contribute here to it.

Let me know whatever you'd like to happen @giuseppe99barchetta.

**Comment by giuseppe99barchetta** [comment]
> It is also a worthy mention that it would require you to get your own repository approved, which can take some time as it's manual. It's normally around a 2 week turn-around, so if you were to do the self-contained approach, we would probably have to work on a cross-over period.

Hi! Thank you for your availability! I’m definitely interested in it. Hosting it here would be much better, as it would allow me to handle all future edits. Since the project is under heavy development, I can't guarantee that the Docker Compose or other main components will remain stable.

What steps do I need to take to get the repository approved?

**Comment by JamsRepos** [comment]
> > It is also a worthy mention that it would require you to get your own repository approved, which can take some time as it's manual. It's normally around a 2 week turn-around, so if you were to do the self-contained approach, we would probably have to work on a cross-over period.
> 
> Hi! Thank you for your availability! I’m definitely interested in it. Hosting it here would be much better, as it would allow me to handle all future edits. Since the project is under heavy development, I can't guarantee that the Docker Compose or other main components will remain stable.
> 
> What steps do I need to take to get the repository approved?

Essentially you just need to set it up as a repository, then seek approval from the main developer Squid on the Unraid forums for approval, he will reply once it's been added. I'll make a PR later today moving everything to here, then you just need to provide Squid with the URL. 

Not sure if he is active on GitHub but his handle here is @Squidly271.

**Comment by giuseppe99barchetta** [comment]
> > > It is also a worthy mention that it would require you to get your own repository approved, which can take some time as it's manual. It's normally around a 2 week turn-around, so if you were to do the self-contained approach, we would probably have to work on a cross-over period.
> > 
> > 
> > Hi! Thank you for your availability! I’m definitely interested in it. Hosting it here would be much better, as it would allow me to handle all future edits. Since the project is under heavy development, I can't guarantee that the Docker Compose or other main components will remain stable.
> > What steps do I need to take to get the repository approved?
> 
> Essentially you just need to set it up as a repository, then seek approval from the main developer Squid on the Unraid forums for approval, he will reply once it's been added. I'll make a PR later today moving everything to here, then you just need to provide Squid with the URL.
> 
> Not sure if he is active on GitHub but his handle here is @Squidly271.

Thank you so much! I'm looking forward to the verification process and the opportunities it will bring. Your support means a lot to me!

**Comment by giuseppe99barchetta** [comment]
> > > It is also a worthy mention that it would require you to get your own repository approved, which can take some time as it's manual. It's normally around a 2 week turn-around, so if you were to do the self-contained approach, we would probably have to work on a cross-over period.
> 
> > 
> 
> > Hi! Thank you for your availability! I’m definitely interested in it. Hosting it here would be much better, as it would allow me to handle all future edits. Since the project is under heavy development, I can't guarantee that the Docker Compose or other main components will remain stable.
> 
> > 
> 
> > What steps do I need to take to get the repository approved?
> 
> 
> 
> Essentially you just need to set it up as a repository, then seek approval from the main developer Squid on the Unraid forums for approval, he will reply once it's been added. I'll make a PR later today moving everything to here, then you just need to provide Squid with the URL. 
> 
> 
> 
> Not sure if he is active on GitHub but his handle here is @Squidly271. 

Hi Jams! Sorry to bother you but I have so many user that asking why they can't find anymore SuggestArr on UnRaid store, could we move forward to the process?

Thank you again!

**Comment by JamsRepos** [comment]
> > > > It is also a worthy mention that it would require you to get your own repository approved, which can take some time as it's manual. It's normally around a 2 week turn-around, so if you were to do the self-contained approach, we would probably have to work on a cross-over period.
> > 
> > 
> > > 
> > 
> > 
> > > Hi! Thank you for your availability! I’m definitely interested in it. Hosting it here would be much better, as it would allow me to handle all future edits. Since the project is under heavy development, I can't guarantee that the Docker Compose or other main components will remain stable.
> > 
> > 
> > > 
> > 
> > 
> > > What steps do I need to take to get the repository approved?
> > 
> > 
> > Essentially you just need to set it up as a repository, then seek approval from the main developer Squid on the Unraid forums for approval, he will reply once it's been added. I'll make a PR later today moving everything to here, then you just need to provide Squid with the URL.
> > Not sure if he is active on GitHub but his handle here is @Squidly271.
> 
> Hi Jams! Sorry to bother you but I have so many user that asking why they can't find anymore SuggestArr on UnRaid store, could we move forward to the process?
> 
> Thank you again!

Seems like someones contribution caused a syntax error, should be back within 2 hours. 

As for this repository, i'll add it now.

**Comment by giuseppe99barchetta** [comment]
> > > > > It is also a worthy mention that it would require you to get your own repository approved, which can take some time as it's manual. It's normally around a 2 week turn-around, so if you were to do the self-contained approach, we would probably have to work on a cross-over period.
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > Hi! Thank you for your availability! I’m definitely interested in it. Hosting it here would be much better, as it would allow me to handle all future edits. Since the project is under heavy development, I can't guarantee that the Docker Compose or other main components will remain stable.
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > What steps do I need to take to get the repository approved?
> > > 
> > > 
> > > Essentially you just need to set it up as a repository, then seek approval from the main developer Squid on the Unraid forums for approval, he will reply once it's been added. I'll make a PR later today moving everything to here, then you just need to provide Squid with the URL.
> > > Not sure if he is active on GitHub but his handle here is @Squidly271.
> > 
> > 
> > Hi Jams! Sorry to bother you but I have so many user that asking why they can't find anymore SuggestArr on UnRaid store, could we move forward to the process?
> > Thank you again!
> 
> Seems like someones contribution caused a syntax error, should be back within 2 hours.
> 
> As for this repository, i'll add it now.

Unfortunately, not yet visible on the store. I have reached out to Squid for verification, and I will keep you updated on the progress.

**Comment by jordan-dalby** [comment]
Can confirm it is now in the store.

**Comment by giuseppe99barchetta** [comment]
> @giuseppe99barchetta It's definetely on the store, I can see it myself.
> 
> image

image

Thank you! 😊 Not sure why, but up until a few days ago, I was able to find it easily by searching here: https://unraid.net/community/apps?q=suggestarr#r now, however, it’s no longer appearing.

**Comment by JamsRepos** [comment]
I would assume that list operates on a different cache level to the actual store front itself. It'll probably show on there in the next few days. 

It probably got removed when whoever done the update for the variables to be removed broke syntax and I simply just missed the syntax error.

**Pull request merged**
